apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: teamsykmelding-mock
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://teamsykmelding-mock.dev.intern.nav.no"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready


